movproject/movapp/urls.py
from django.urls import path

from . import views
app_name='movapp'

urlpatterns = [
    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete'),
]

movproject/movproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("movapp.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movproject/movapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    objects = None
    name=models.CharField(max_length=250)
    disc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

movproject/movapp/forms.py
from django import forms
from .models import Movie


class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','disc','year','img']

movproject/movapp/views.py
from django.shortcuts import render, redirect

from .forms import MovieForm
from .models import Movie
# Create your views here.
def index(request):
    movie = Movie.objects.all()
    context = {
        'movie_list': movie
    }
    return render(request,'index.html',context)
def detail(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render(request,"detail.html",{'movie':movie})
def add_movie(request):
    if request.method=="POST":
        name=request.POST.get('name',)
        disc = request.POST.get('disc',)
        year = request.POST.get('year',)
        img = request.FILES['img']
        movie=Movie(name=name,disc=disc,year=year,img=img)
        movie.save()
    return render(request,'add.html')
def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None, request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})

def delete(request,id):
    if request.method=='POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

movproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="text" name="name" placeholder="Enter Movie Name"><br>
    <input type="text" name="disc" placeholder="Enter Movie Description"><br>
    <input type="text" name="year" placeholder="Release Year"><br>
  <input type="file" name="img"><br>
  <input type="submit">
</form>
{% endblock %}

movproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      Movie Store
    </a>
  </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movproject/templates/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="POST">
    {% csrf_token %}
    Are You Want to Delete This Movie?
    <input type="submit">
</form>

</body>
</html>

movproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" width="300" height="450">
        </div>
            <div class="col-md-6">
            <h3>{{movie.name}}</h3>
            <h4>{{movie.disc}}</h4>
            <h6>{{movie.year}}</h6>
            <a class="btn btn-warning" href="{% url 'movapp:update' movie.id %}">Update</a>
            <a class="btn btn-danger" href="{% url 'movapp:delete' movie.id %}">Delete</a>
        </div>
    </div>
</div>
{% endblock %}

movproject/templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

movproject/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        {% for i in movie_list %}

        <div class="col-md-3">
            <div class="card" style="width: 18rem;">
  <img src="{{i.img.url}}" class="card-img-top" alt="" height="300px">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.disc}}</p>
    <a href="{% url 'movapp:detail' i.id %}" class="btn btn-primary">Go somewhere</a>
  </div>
</div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}